### ISSUE TITLE
dnf is not mimimal on certain function

### ISSUE THREAD

**Issue by MFridlyand** [madmann91/minbool#1]
Let's take the function f(x1 , x2 , x3) = (x1 and x2 and x3) xor (x1 and x2) xor 1, it has following  mimimal DNF (!x1 or !x2 or x3),  but your algorithm returns !x1 or !x2 or (x1 and x2 and x3). I have debugged your code and probably found the root of the problem: You have Nbits + 1 groups, but you need also  Nbits + 2 ranges, to implemet combine logic. Check the code below i think it solves the problem correctly.

template <size_t Nbits>
struct ImplicantTable {
    using MinTermN = MinTerm<Nbits>;

    size_t groups[Nbits + 1];
    size_t borders[Nbits + 2];
    std::vector<bool>     marks;
    std::vector<MinTermN> terms;

    size_t size() const { return terms.size(); }

    void fill(const std::vector<MinTermN>& minterms) {
        std::fill(groups, groups + Nbits + 1, 0);
		std::fill(borders, borders + Nbits + 2, 0);
        for (auto& term : minterms)
            groups[popcount(term.value)]++;
        std::partial_sum(groups, groups + Nbits + 1, groups);
		std::copy(groups, groups + Nbits + 1, borders + 1);
        terms.resize(minterms.size());
        marks.resize(minterms.size());
        for (auto& term : minterms)
            terms[--groups[popcount(term.value)]] = term;
    }

    void combine(std::vector<MinTermN>& res) {
        for (size_t i = 0; i < Nbits; ++i) {
            for (size_t j = borders[i]; j < borders[i + 1]; ++j) {
                for (size_t k = borders[i + 1]; k < borders[i + 2]; ++k) {
                    auto& term_a = terms[j];
                    auto& term_b = terms[k];
                    if ((term_a.value & term_b.value) == term_a.value && (term_a.dash == term_b.dash)) {
                        marks[j] = true;
                        marks[k] = true;
						auto cmb = term_a.combine(term_b);
                        res.push_back(cmb);
                    }
                }
            }
        }
    }

**Comment by madmann91** [comment]
Thank you for reporting! I will have a look once I get the time.

**Comment by madmann91** [comment]
You were right, the implicant table was missing the last group. This is now fixed in commit 98dd65d43f57743b5ee88e3c6fdfb218ec9e1c8e.
